"""descuentos_obras_sociales_por_profesional

Revision ID: 71c64c55323d
Revises: a1b2c3d4e5f6
Create Date: 2026-06-11 13:10:42.515749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71c64c55323d'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profesionales', sa.Column('descuentos_obras_sociales', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profesionales', 'descuentos_obras_sociales')
    # ### end Alembic commands ###
