"""drop_cola_analisis_seguimientos

Revision ID: adeda5eeebdc
Revises: a1b2c3d4e5f6
Create Date: 2026-06-11 16:24:46.727690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adeda5eeebdc'
down_revision: Union[str, None] = '71c64c55323d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_seguimientos_id', table_name='seguimientos')
    op.drop_table('seguimientos')
    op.drop_table('cola_analisis')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cola_analisis',
    sa.Column('cliente_id', sa.VARCHAR(), nullable=False),
    sa.Column('fecha_ultima_actividad', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('cliente_id')
    )
    op.create_table('seguimientos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('cliente_id', sa.VARCHAR(), nullable=True),
    sa.Column('estado', sa.VARCHAR(), nullable=True),
    sa.Column('fecha_programada', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_seguimientos_id', 'seguimientos', ['id'], unique=False)
    # ### end Alembic commands ###
