"""add_turnos

Revision ID: dd44e5dbe40a
Revises: 4faaa4399732
Create Date: 2026-06-09 23:59:19.258415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd44e5dbe40a'
down_revision: Union[str, None] = '4faaa4399732'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turnos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('profesional_id', sa.String(), nullable=False),
    sa.Column('cliente_id', sa.String(), nullable=True),
    sa.Column('empresa_id', sa.String(), nullable=False),
    sa.Column('fecha_hora_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_hora_fin', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['profesional_id'], ['profesionales.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profesional_id', 'fecha_hora_inicio', name='uq_turno_profesional_hora')
    )
    op.add_column('clientes', sa.Column('profesional_id', sa.String(), nullable=True))
    op.add_column('clientes', sa.Column('bot_activo', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'clientes', 'profesionales', ['profesional_id'], ['id'])
    op.create_unique_constraint(None, 'empresas', ['phone_number_id'])
    op.add_column('mensajes', sa.Column('empresa_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'mensajes', 'empresas', ['empresa_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mensajes', type_='foreignkey')
    op.drop_column('mensajes', 'empresa_id')
    op.drop_constraint(None, 'empresas', type_='unique')
    op.drop_constraint(None, 'clientes', type_='foreignkey')
    op.drop_column('clientes', 'bot_activo')
    op.drop_column('clientes', 'profesional_id')
    op.drop_table('turnos')
    # ### end Alembic commands ###
