"""estado_inicial

Revision ID: e085c6052f22
Revises: 
Create Date: 2026-05-29 17:23:19.983327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e085c6052f22'
down_revision: Union[str, None] = 'c0000000000a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profesionales',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('empresa_id', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('especialidad', sa.String(), nullable=False),
    sa.Column('tarifa_particular', sa.Integer(), nullable=False),
    sa.Column('tarifa_obra_social', sa.Integer(), nullable=False),
    sa.Column('calendar_id', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('clientes', sa.Column('profesional_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'clientes', 'profesionales', ['profesional_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clientes', type_='foreignkey')
    op.drop_column('clientes', 'profesional_id')
    op.drop_table('profesionales')
    # ### end Alembic commands ###
